[tools]
rust = "beta"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
rust-analyzer = "latest"
pre-commit = "latest"
"cargo:cargo-bundle" = "latest"
xcodegen = { version = "latest", os = ["macos"] }
