[tools]
rust = "beta"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
rust-analyzer = "latest"
pre-commit = "latest"
"cargo:cargo-bundle" = "latest"
xcodegen = { version = "latest", os = ["macos"] }
"cargo:cargo-audit" = "latest"
prek = "latest"
"github:release-plz/release-plz" = "latest"

[tasks.pre-commit-install]
description = "Install pre-commit hooks"
run = "prek install -f --hook-type pre-commit --hook-type pre-push"
