[package]
name = "csm-tui"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "csm-tui"
path = "src/main.rs"

[features]
default = ["sentry"]
sentry = ["common/sentry"]

[dependencies]
common = { version = "0.2.0", path = "../common", default-features = false }
ratatui = "0.30"
clap = { version = "4", features = ["derive", "env"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
